name: Main Workflow

on:
  schedule:
    - cron: "10 0 * * *" # Runs every day
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 200

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Debug Environment Variables
      #   run: |
      #     echo "Checking SERVICES_GCLOUD_KEY_JSON..."
      #     echo $ELECTRONICS_GCLOUD_KEY_JSON | head -c 50
      
      - name: Install Playwright for Python
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install
      
      - name: Run the scraper
        env:
          JOBS_GCLOUD_KEY_JSON: ${{ secrets.JOBS_GCLOUD_KEY_JSON }}
        run: |
          python jobs_main.py
      
      - name: Run the scraper2
        env:
          OTHERS_GCLOUD_KEY_JSON: ${{ secrets.OTHERS_GCLOUD_KEY_JSON }}
        run: |
          python others_main.py
      
      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scraper-logs
          path: scraper.log
